DONE модуль 1 задания 1-5
js-tasks-ru/jsbasic-20220711_serge-aleksis pull request #2
Opened 2022-07-18 19:44 UTC by sergealeksis

не получилось сразу отправить все, поэтому двумя частями))

2022-07-18 19:45 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-07-18 20:22 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-07-19 04:16 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-07-19 14:28 UTC, SinimaWath requested changes

2022-07-19 14:28 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  }
тут else лишний, давай перепишем проще и без него: 
```
if (n > 0) {
 ....
 return n;
}

return 1;
```

2022-07-19 14:28 UTC, SinimaWath commented on 1-module/3-task/index.js
> +    }
else тут лишний:
```
if (str) {
   return ....;
}
   return ...;
```

2022-07-19 14:28 UTC, SinimaWath commented on 1-module/4-task/index.js
> +if (lowText.includes('1xbet') || lowText.includes('xxx')) {
`lowText.includes('1xbet') || lowText.includes('xxx')` - это уже boolean, поэтому if тут лишний"
`return lowText.includes('1xbet') || lowText.includes('xxx')`

2022-07-19 14:28 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  } else {
тут тоже давай без else

2022-07-19 22:03 UTC, closed without merging

2022-07-19 22:04 UTC, sergealeksis commented
спасибо,  замечания учёл, направлю в следующем пулу-реквест